### ISSUE TITLE
Config options for Slack API

### ISSUE THREAD

**Issue by joenas** [matrix-org/go-neb#202]
I've been trying to get the Slack webhooks to work and the sample config is wrong. 
This is what works for me:

```
- ID: "slackapi_service"
  Type: "slackapi"
  UserID: "@slackbot:localhost"
  Config:
    room_id: "!someroomid:localhost"
    message_type: "m.notice" # default is m.text
```

Also, the webhookUrl isn't printed somewhere (as far as I can tell) so you have to craft it with something like [this](https://play.golang.org/p/ys-fdMA4lz)
```go
package main

import (
	"encoding/base64"
	"fmt"
)

func main() {
	input := "slackapi_service"
	b64data := base64.RawURLEncoding.EncodeToString([]byte(input))
	fmt.Println(b64data)
}
```

I don't know go, I found a similar example [here](https://stackoverflow.com/a/31035384)
