### ISSUE TITLE
Cannot configure sending messages from alertmanager to matrix

### ISSUE THREAD

**Issue by ushacow** [matrix-org/go-neb#259]
Hi! 

I don't completely understand how to configure alertmanager or go-neb to send notifications to synapse. 
I have a running go-neb bot configured as in example in docs with type of service "alertmanager":
```
curl -X POST 10.215.1.1:4050/admin/configureClient --data-binary '{
    "UserID": "@alertmanager:my_synapse_server",
    "HomeserverURL": "https://my_synapse_server",
    "AccessToken": "alertmanager_user_token",
    "Sync": true,
    "AutoJoinRooms": true,
    "DisplayName": "alertmanager"
}'
curl -X POST 10.215.1.1:4050/admin/configureService --data-binary '{
    "Type": "alertmanager",
    "Id": "42",
    "UserID": "@alertmanager:my_synapse_server",
    "Config": {}
}'
```
And I have configured alertmanager:
```
route:
  receiver: 'go-neb'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: [cluster, alertname]

receivers:
- name: 'go-neb'
  webhook_configs:
  - send_resolved: true
    url: 'http://10.215.1.1:4050'
```
Errors from the alertmanager:
```
level=error ts=2018-12-27T15:46:16.378513787Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 404 from http://10.215.1.1:4050"
level=error ts=2018-12-27T15:46:16.378751698Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 404 from http://10.215.1.1:4050"
```

But I don't understand where should I put rooms id to send notifications on alertmanager side or go-neb side? Could you clarify it? There is very short docs on this. Thanks!
