### ISSUE TITLE
Documentation/Examples for AlertManager Integration

### ISSUE THREAD

**Issue by lsnow2017** [matrix-org/go-neb#264]
I am struggling to connect my AlertManager install to the matrix bot. I have the following configs:

config.sample.yaml:
```
clients:
  - UserID: "@jeeves:matrix.mydomain.com"
    AccessToken: "<token>"
    HomeserverURL: "https://matrix.mydomain.com"
    Sync: true
    AutoJoinRooms: true
    DisplayName: "Jeeves"
services:  
   - ID: "prom_alerts"
     Type: "alertmanager"
     UserID: "@jeeves:matrix.mydomain.com"
     Config:
      webhook_url: "/prom_alerts"`
```

And for alert manager:
```
receiver: 'jeeves-webhook'
  routes:
  - match:
      service: logan-alert
    receiver: 'jeeves-webhook'

receivers:
- name: "jeeves-webhook"
  webhook_configs:
  - url: 'https://alerts.mydomain.com/services/hooks/cHJvbV9hbGVydHM'
    send_resolved: true
```

When the webhook fires I get this error from the bot output:
`INFO[0025] Failed to load service                        error=sql: no rows in result set service_id=prom_alerts`

Some additional documentation/any guidance would be great. Thank you!
