### ISSUE TITLE
Support for Sentry webhooks

### ISSUE THREAD

**Issue by va3093** [matrix-org/go-neb#342]
**Describe the solution you'd like**
Sentry makes the following webhook call https://docs.sentry.io/product/integrations/integration-platform/webhooks/. It would be amazing if we could point this webhook towards GO-neb. We currently use the alert manager webhook. So it would be great to use it in the same way for sentry.

```yaml
services:
  - ID: "alertmanager_service"
    Type: "alertmanager"
    UserID: "@bot:xxx.modular.im"
    Config:
      webhook_url: "http://matrix-bot.monitoring/services/hooks/xxx"
      rooms:
        "${room_id}:xxx.modular.im":
          text_template: "{{range .Alerts -}} [{{ .Status }}] {{index .Labels \"alertname\" }}: {{index .Annotations \"description\"}} {{ end -}}"
          html_template: "{{range .Alerts -}}  {{ $severity := index .Labels \"severity\" }}    {{ if eq .Status \"firing\" }}      {{ if eq $severity \"critical\"}}        <font color='red'><b>[FIRING - CRITICAL]</b></font>      {{ else if eq $severity \"warning\"}}        <font color='orange'><b>[FIRING - WARNING]</b></font>      {{ else }}        <b>[FIRING - {{ $severity }}]</b>      {{ end }}    {{ else }}      <font color='green'><b>[RESOLVED]</b></font>    {{ end }}  {{ index .Labels \"alertname\"}} : {{ index .Annotations \"description\"}}   <a href=\"{{ .GeneratorURL }}\">source</a><br/>{{end -}}"
  - ID: "sentry"
    Type: "sentry"
    UserID: "@bot:xxx.modular.im"
    Config:
      webhook_url: "http://matrix-bot.monitoring/services/hooks/xxx"
      rooms:
        "${room_id}:xxx.modular.im":
          text_template: "{{index .Annotations \"description\"}} {{ end -}}"
          html_template: "<font color='red'><b>[Error]</b></font> {{ index .Annotations \"description\"}}   <a href=\"{{ .GeneratorURL }}\">source</a><br/>{{end -}}"
```

**Describe alternatives you've considered**
Considering using this for the time being: https://github.com/matrix-org/matrix-sentry-webhooks

**Additional context**
