### ISSUE TITLE
go-neb not encrypting messages

### ISSUE THREAD

**Issue by ibotty** [matrix-org/go-neb#380]
**Describe the bug**

I want go-neb to use an old account and send encrypted messages to a private room, set to be encrypted.

Posting to the room works fine, but the messages are not encrypted.

I am using a config like the following.
```
clients:
  - UserID: "@bot-alertmanager-matrix:<redacted>"
    AccessToken: "<redacted>"
    DeviceID: "go-neb1"
    HomeserverURL: "https://<redacted>"
    Sync: false
    AutoJoinRooms: false
    DisplayName: "Cluster Alerts bot"
    AcceptVerificationFromUsers: ["@ibotty:<redacted>"]

services:

  - ID: "alertmanager_service"
    Type: "alertmanager"
    UserID: "@bot-alertmanager-matrix:<redacted>"
    Config:
      webhook_url: "http://go-neb.matrix.svc.cluster.local:4050/services/hooks/YWxlcnRtYW5hZ2VyX3NlcnZpY2U="
      # Each room will get the notification with the alert rendered with the given template
      rooms:
        "!<redacted>:<redacted>":
          text_template: "{{range .Alerts -}} [{{ .Status }}] {{index .Labels \"alertname\" }}: {{index .Annotations \"description\"}} {{ end -}}"
          html_template: "{{range .Alerts -}}  {{ $severity := index .Labels \"severity\" }}    {{ if eq .Status \"firing\" }}      {{ if eq $severity \"critical\"}}        <font color='red'><b>[FIRING - CRITICAL]</b></font>      {{ else if eq $severity \"warning\"}}        <font color='orange'><b>[FIRING - WARNING]</b></font>      {{ else }}        <b>[FIRING - {{ $severity }}]</b>      {{ end }}    {{ else }}      <font color='green'><b>[RESOLVED]</b></font>    {{ end }}  {{ index .Labels \"alertname\"}} : {{ index .Annotations \"description\"}}   <a href=\"{{ .GeneratorURL }}\">source</a><br/>{{end -}}"
          msg_type: "m.text"  # Must be either `m.text` or `m.notice`
```
